// Generated by https://quicktype.io

export interface Cart {
  restaurant_id: number;
  /** 없어도 되는거 아님? */
  restaurant?: Restaurant;
  restaurant_name: string;
  default_price: number;
  checkout_address: CheckoutAddress;
  stock_amount_dictionary: StockAmountDictionary;
  items: CartItem[];
}

export interface CheckoutAddress {
  address: string; // 서울특별시 강남구 역삼동 826-28 송민빌딩
  zipcode: string; // 135081
}

export interface CartItem {
  price: number;
  base_price: number;
  default_price: number;
  name: string;
  slug: string;
  id: number;
  amount: number;
  subchoices: { [slug: string]: Subchoice };
  id_for_stock: number;
}

export interface Subchoice {
  slug: string;
  name: string;
  multiple: boolean;
  items: SubchoiceItem[];
}

export interface SubchoiceItem {
  slug: string;
  name: string;
  price: number;
  soldout: boolean;
  id: number;
  description: string;
}

export interface Restaurant {
  rating: number;
  detail_image_urls: string[];
  subtitle: string;
  floating_message: string;
  delivery_fee: number;
  is_available_delivery: boolean;
  discounted_delivery_fee: number;
  open: boolean;
  hygiene_grade: null;
  city: string;
  delivery_fee_notice: DeliveryFeeNotice;
  delivery_fee_explanation: null;
  franchise_id: number;
  history_message: string;
  has_disposable_menu: boolean;
  franchise_name: string;
  review_image_count: number;
  is_available_pickup: boolean;
  undeliverable_reason: string;
  additional_discount_per_menu: number;
  opening_times: any[];
  additional_discount_pickup: number;
  phone: string;
  has_terminal: boolean;
  discount_until: null;
  categories: string[];
  is_open_all_day: boolean;
  min_order_amount: number;
  distance: number;
  minimum_pickup_minutes: number;
  except_cash: boolean;
  name: string;
  has_flyers: boolean;
  delivery_method: string;
  owner_reply_count: number;
  discount_percent: number;
  delivery_fee_to_display: Display;
  open_all_day_until: null;
  free_delivery_threshold: number;
  dine_in: boolean;
  has_liquor_section: boolean;
  stock_management: boolean;
  use_reusable_packaging: boolean;
  additional_discount_pickup_per_menu: number;
  open_time_description: string;
  zones: null;
  adjusted_delivery_fee: number;
  app_order: boolean;
  lng: number;
  restaurant_type: string;
  id: number;
  can_review: number;
  estimated_delivery_time: string;
  review_count: number;
  discount_from: null;
  is_deliverable: boolean;
  tags: string[];
  reachable: boolean;
  additional_discount: number;
  new: boolean;
  logo_url: string;
  central_billing: boolean;
  begin: string;
  description: string;
  unorderable_under_min_order_value: boolean;
  background_url: string;
  phone_order: boolean;
  address: string;
  lat: number;
  end: string;
  slug: string;
  review_avg: number;
  thumbnail_message: string;
  url: string;
  payment_methods: string[];
}

export interface DeliveryFeeNotice {
  by_price: ByPrice[];
}

export interface ByPrice {
  to: string;
  amount: number;
  from: string;
  display: Display;
}

export interface Display {
  basic: string;
}

export interface StockAmountDictionary {}
