// Generated by https://quicktype.io

export interface Location {
  updated_at: number;
  address: string;
  address_input: string;
  point: Point;
  method: string;
  zipcode: string;
  district: string[];
  dongmyun: string;
  sido: string;
  adiyo: Adiyo;
}

export interface Adiyo {
  law: Admin;
  point: Point;
  road: Admin;
  admin: Admin;
  zipcode: string;
  display_address_long: string;
  display_address_short: string;
}

export interface Admin {
  sido: string;
  sigugun: string;
  dongmyun: string;
  ri: string;
  detail: string;
}

export interface Point {
  lat: number;
  lng: number;
}
