// Generated by https://quicktype.io

export interface ShopDetailedInfo {
  min_order_amount: number;
  nutrition_fact_desktop_url: string;
  violations: null;
  except_cash: boolean;
  description: string;
  tags: any[];
  opening_time_description: string;
  suspension_text: null;
  allergy_info_mobile_url: string;
  phone: string;
  nutrition_fact_mobile_url: string;
  crmdata: ShopCrmdata;
  address: string;
  allergy_info_desktop_url: string;
  introduction_by_owner: ShopIntroductionByOwner;
  lng: number;
  lat: number;
  country_origin: string;
}

export interface ShopCrmdata {
  company_name: string;
  company_number: string;
}

export interface ShopIntroductionByOwner {
  images: ShopImage[];
  introduction_text: string;
}

export interface ShopImage {
  thumbnail_url: string;
  image_url: string;
}
