// Generated by https://quicktype.io

export interface ShopMenu {
  items: Menu[];
  slug: string;
  name: string;
  description?: null | string;
  image?: null;
  ms_type?: null;
}

export interface Menu {
  subtitle: string;
  description: string;
  top_displayed_item_order: number | null;
  price: string;
  slug: string;
  one_dish: boolean;
  id: number;
  section: string;
  subchoices: MenuItemSubchoice[];
  review_count: number;
  reorder_rate_message: string;
  industrial_info: MenuIndustrialInfo;
  soldout: boolean;
  name: string;
}

export interface MenuIndustrialInfo {}

export interface MenuItemSubchoice {
  mandatory: boolean;
  name: string;
  multiple_count: number;
  is_available_quantity: boolean;
  subchoices: SubchoiceSubchoice[];
  multiple: boolean;
  slug: string;
}

export interface SubchoiceSubchoice {
  slug: string;
  name: string;
  price: string;
  soldout: boolean;
  id: number;
  description: string;
}
