// Generated by https://quicktype.io

/** 메뉴 카테고리(API 응답) */
export interface ShopMenuCat {
  /** 메뉴 목록 */
  items: Menu[];
  slug: string;
  /** 카테고리 이름 */
  name: string;
  /** 기본 설명 */
  description?: null | string;
  image?: any;
  ms_type?: any;
}

/** 메뉴 1개 */
export interface Menu {
  subtitle: string;
  /** 메뉴 설명 */
  description: string;
  /** 순서 결정용 */
  top_displayed_item_order: number | null;
  /** 가격(KRW) */
  price: string;
  slug: string;
  one_dish: boolean;
  /** 메뉴 구분자 */
  id: number;
  /** 메뉴가 속한 섹션의 이름 */
  section: string;
  /** 하위 옵션 */
  subchoices: MenuSubchoiceGroup[];
  /** 리뷰 갯수? */
  review_count: number;
  reorder_rate_message: string;
  industrial_info: any;
  /** 품절 */
  soldout: boolean;
  /** 메뉴 이름 */
  name: string;
  image: any; // DEBUG
}

/** 메뉴 옵션의 모임 */
export interface MenuSubchoiceGroup {
  /** 선택 해제 불가 */
  mandatory: boolean;
  /** 선택 종류 */
  name: string;
  /** 최대 동시 선택 가능 수량 */
  multiple_count: number;
  /** 남은 수량 표시 */
  is_available_quantity: boolean;
  /** 옵션 선택지 */
  subchoices: MenuSubchoice[];
  /** 복수 선택 가능 */
  multiple: boolean;
  slug: string;
}

/** 메뉴 옵션 */
export interface MenuSubchoice {
  slug: string;
  /** 메뉴 이름 */
  name: string;
  /** 가격 */
  price: string;
  /** 매진 여부 */
  soldout: boolean;
  /** 메뉴의 고유 키 */
  id: number;
  description: string;
}

export interface SubchoiceSubchoice {
  slug: string;
  name: string;
  price: string;
  soldout: boolean;
  id: number;
  description: string;
}
